services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: php game.php

  dev:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    stdin_open: true
    tty: true

  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: composer test